version: '3.6'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - D:\BackEndProject\frostmourne\doc\docker\mydata:/var/lib/mysql
  frostmourne-monitor:
    image: frostmourne/frostmourne
    container_name: frostmourne-monitor
    links:
      - mysql:ms #可以用es这个域名访问elasticsearch服务
    environment:
      datasource_frostmourne_url: jdbc:mysql://host.docker.internal:3306/frostmourne?useSSL=false&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      datasource_frostmourne_username: root
      datasource_frostmourne_password: root
      frostmourne_monitor_address: http://localhost:10054
      initial_password: 123456
      alarmlog_reserve_days: 30
      ldap_enabled: 'false'
      spring_ldap_urls:
      spring_ldap_username:
      spring_ldap_password:
      spring_ldap_base:
      spring_ldap_auth_searchFilter:
      frostmourne_message_title:
      email.smtp-host: smtp.qq.com
      email.smtp-port: 25
      email.smtp-auth: 'true'
      email.sender: xxx@qq.com
      email.sender-password: xxx
      wechat.corpid:
      wechat.agentid:
      wechat.secret:
    ports:
      - '10054:10054'
    expose:
      - '10054'
    networks:
      frostmourne_net:
    command: bash -c "/opt/frostmourne/start.sh"

networks:
  frostmourne_net:
